export const backgroundQuestions = [

    {
        id: "known_tech",
        question: "Which technologies are you already comfortable with?",
        type: "multiselect",
        options: [
            // Most Popular Core Tools
            "JavaScript",
            "Python",
            "VS Code", 
            "GitHub",
            "Git",
            "React",
            "Node.js",
            "TypeScript",
            "HTML/CSS",
            "Docker",
            "ChatGPT",
            "GitHub Copilot",
            "PostgreSQL",
            "AWS",
            "MongoDB",
            "Tailwind CSS",
            "Next.js",
            "Figma",
            "Angular",
            "Vue.js",
            "Express.js",
            "Jest",
            "Cypress",
            "Django",
            "Claude",
            "Gemini",
            "OpenAI API",
            "Azure",
            "Google Cloud",
            "Kubernetes",
            "Vercel",
            "Notion",
            "Redux",
            "Spring Boot",
            "Java",
            "GraphQL",
            "Jira",
            "IntelliJ IDEA",
            "PyCharm",
            "Netlify",
            "Heroku",
            "CI/CD",
            "Playwright",
            "Postman",
            "Selenium",
            "Miro",
            "Draw.io",
            "WebStorm",
            "Eclipse",
            "Android Studio",
            "Xcode",
            "Cursor",
            "npm/yarn",
            "Tabnine",
            "Amazon Q Developer",
            "Codeium",
            "Bito AI",
            "Mistral AI",
            "Llama 3",
            "Perplexity",
            "Anthropic API",
            "Datadog",
            "Sentry",
            "New Relic",
            "Prometheus",
            "LogRocket",
            "Replit Ghostwriter",
            "Copilot.Live",
            "Sourcegraph Cody",
            
            // DevOps & Infrastructure Tools
            "Terraform",
            "Ansible",
            "Jenkins",
            "GitLab CI/CD",
            "GitHub Actions",
            "Grafana",
            "OpenTelemetry",
            "Argo CD",
            "Tekton",
            "Harness",
            "Crossplane",
            "AWS Lambda",
            "Azure Functions",
            "Google Cloud Functions",
            "Serverless Framework",
            "Pulumi",
            "HyperDX",
            "Dash0",
            "AWS CloudWatch",
            "Elasticsearch",
            "Kibana",
            "Splunk",
            "Sumo Logic",
            "Dynatrace",
            "AppDynamics",
            
            // Data Science & ML Tools
            "NumPy",
            "Pandas",
            "Scikit-learn",
            "TensorFlow",
            "PyTorch",
            "Keras",
            "Matplotlib",
            "Seaborn",
            "Jupyter Notebooks",
            "Google Colab",
            "XGBoost",
            "LightGBM",
            "NLTK",
            "spaCy",
            "Hugging Face Transformers",
            "Ray",
            "MLflow",
            "DVC",
            "Weights & Biases", 
            "Dask",
            
            // Game Development
            "Unity",
            "Unreal Engine",
            "Godot",
            "GameMaker Studio",
            "Blender",
            "Maya",
            "3DS Max",
            "ZBrush",
            "Substance Painter",
            "RPG Maker",
            
            // Web3 & Blockchain Development
            "Solidity",
            "Web3.js",
            "Ethers.js",
            "Hardhat",
            "Truffle",
            "Foundry",
            "Remix IDE",
            "OpenZeppelin",
            "Metamask",
            "Alchemy",
            
            // No-Code & Low-Code Platforms
            "Zapier",
            "Airtable",
            "Bubble",
            "Webflow",
            "Retool",
            "Appsmith",
            "n8n",
            "Make (Integromat)",
            "Power Apps",
            "Directual",
            
            // MLOps & AI Engineering
            "Kubeflow",
            "Airflow",
            "BentoML",
            "Dagster",
            "Prefect",
            "Label Studio",
            "Seldon Core"
          ],

        
        allowCustomInput: true
    },
        // {
    //     id: "experience",
    //     question: "What's your programming experience level?",
    //     type: "select",
    //     options: [
    //         "Beginner (Can write basic code)",
    //         "Intermediate (Build full applications)",
    //         "Advanced (Architect complex systems)"
    //     ],
    //     // followUp: {
    //     //     if: "Beginner",
    //     //     ask: "Would you prefer no-code/low-code solutions when possible?",
    //     //     options: ["Yes", "No"]
    //     // }
    // },
    // {
    //     id: "time_commitment",
    //     question: "Weekly development hours available:",
    //     type: "slider",
    //     min: 2,
    //     max: 40,
    //     step: 1,
    //     labels: {
    //         2: "2h (Weekends)",
    //         20: "20h (Part-time)",
    //         40: "40h (Full-time)"
    //     }
    // },
    // {
    //     id: "risk_tolerance",
    //     question: "Do you prioritize:",
    //     type: "select",
    //     options: [
    //         "Speed (Ship fast, even if basic)",
    //         "Scalability (Build for future growth)",
    //         "Learning (Optimize for skill development)"
    //     ]
    // },
    // {
    //     id: "collaboration",
    //     question: "How will you work?",
    //     type: "select",
    //     options: [
    //         "Solo developer",
    //         "Small team (2-5 people)",
    //         "Large team (5+ people)"
    //     ]
    // }
];